### ISSUE TITLE
Resuming doesn't work

### ISSUE THREAD

**Issue by dtonderski** [dtonderski/dynamic-fusion#3]
Getting:
```
INFO:TrainingMonitor:Starting at iteration 0
Traceback (most recent call last):
  File "/home/davton/dev/dynamic-fusion/main.py", line 55, in <module>
    main(args)
  File "/home/davton/dev/dynamic-fusion/main.py", line 35, in main
    return train_reconstruction(arguments)
  File "/home/davton/dev/dynamic-fusion/main.py", line 24, in train_reconstruction
    network_trainer.run()
  File "/home/davton/dev/dynamic-fusion/dynamic_fusion/network_trainer/trainer.py", line 26, in run
    self.network_fitter.run(data_loader, reconstruction_network, decoding_network)
  File "/home/davton/dev/dynamic-fusion/dynamic_fusion/network_trainer/network_fitter.py", line 70, in run
    self._reconstruction_step(
  File "/home/davton/dev/dynamic-fusion/dynamic_fusion/network_trainer/network_fitter.py", line 164, in _reconstruction_step
    optimizer.step()
  File "/home/davton/miniconda3/envs/thesis2/lib/python3.9/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/davton/miniconda3/envs/thesis2/lib/python3.9/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/davton/miniconda3/envs/thesis2/lib/python3.9/site-packages/torch/optim/adam.py", line 234, in step
    adam(params_with_grad,
  File "/home/davton/miniconda3/envs/thesis2/lib/python3.9/site-packages/torch/optim/adam.py", line 300, in adam
    func(params,
  File "/home/davton/miniconda3/envs/thesis2/lib/python3.9/site-packages/torch/optim/adam.py", line 363, in _single_tensor_adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
when resuming training after adding decoding network.

**Comment by dtonderski** [comment]
Closed by afc76c3
